name: CI Workflow for Testing

on:
  push:
    branches:
      - main # หรือเลือก branch ที่ต้องการจะทำงานกับ GitHub Actions
  pull_request:
    branches:
      - main # หรือเลือก branch ที่ต้องการจะทำงานกับ GitHub Actions

jobs:
  test:
    runs-on: ubuntu-latest # เลือกระบบปฏิบัติการที่คุณต้องการ เช่น Ubuntu, Windows, macOS

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "18.20.3" 

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm run test